name: portafolio_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  change_app_package_name: ^1.1.0
  dio: ^5.4.3+1
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.1.1
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  formz: ^0.7.0
  go_router: ^13.2.4
  # google_fonts: ^6.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/icons/topBar/
    # - assets/images/
    # - assets/fonts/